// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.PNG" {
  const path: string;
  export = path;
}

declare module "*.png" {
  const path: string;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

/**
 * Imported for its side effect (the bundler injects the stylesheet); it has no shape.
 */
declare module "*.css";
